CREATE TABLE IF NOT EXISTS course (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB;

insert into course(id,name) values(1000, 'spring boot');

CREATE TABLE IF NOT EXISTS student (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS passport (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`number` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS review (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`rating` VARCHAR(255),
	`description` VARCHAR(255),
	PRIMARY KEY (`id`)
)ENGINE=InnoDB;
